name: Publish zip to release

on:
  release:
    types:
    - published
    branches:
    - main

jobs:
  createZip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.3.4
      with:
        ref: main
    - name: Zip old files
      working-directory: './GridBlocks/itemsadder-old'
      run: zip -r GridBlocks-${{ github.event.release.tag_name }}-old.zip data/'
    - name: Zip new files
      working-directory: './GridBlocks/itemsadder-new'
      run: zip -r GridBlocks-${{ github.event.release.tag_name }}-new.zip gridblocks/
    - name: Upload zip to release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'GridBlocks/itemsadder-old/GridBlocks-${{ github.event.release.tag_name }}-old.zip;GridBlocks/itemsadder-new/GridBlocks-${{ github.event.release.tag_name }}-new.zip'
        repo-token: '${{ secrets.GITHUB_TOKEN }}'